var	core = require('./core');

module.exports = core.generateApi([
	'hotel.add',
	'hotel.city.get',
	'hotel.get',
	'hotel.image.upload',
	'hotel.match.feedback',
	'hotel.name.get',
	'hotel.order.booking.feedback',
	'hotel.order.face.check',
	'hotel.order.face.deal',
	'hotel.order.get',
	'hotel.order.pay.feedback',
	'hotel.order.refund.feedback',
	'hotel.orders.search',
	'hotel.room.add',
	'hotel.room.get',
	'hotel.room.img.delete',
	'hotel.room.img.upload',
	'hotel.room.quotas.query.feedback',
	'hotel.room.update',
	'hotel.rooms.search',
	'hotel.rooms.update',
	'hotel.sold.hotels.increment.get',
	'hotel.sold.orders.increment.get',
	'hotel.sold.types.increment.get',
	'hotel.type.add',
	'hotel.type.name.get',
	'hotel.update',
	'hotels.search'
]);
