var	core = require('./core');

module.exports = core.generateApi([
	{
		method: 'aftersale.get'
	}, {
		method: 'item.add'
	}, {
		method: 'item.anchor.get'
	}, {
		method: 'item.bseller.add'
	}, {
		method: 'item.cseller.add'
	}, {
		method: 'item.delete'
	}, {
		method: 'item.get'
	}, {
		method: 'item.img.delete'
	}, {
		method: 'item.img.upload'
	}, {
		method: 'item.joint.img'
	}, {
		method: 'item.joint.propimg'
	}, {
		method: 'item.price.update'
	}, {
		method: 'item.propimg.delete'
	}, {
		method: 'item.propimg.upload'
	}, {
		method: 'item.quantity.update'
	}, {
		method: 'item.recommend.add'
	}, {
		method: 'item.recommend.delete'
	}, {
		method: 'item.sku.add'
	}, {
		method: 'item.sku.delete'
	}, {
		method: 'item.sku.get'
	}, {
		method: 'item.sku.price.update'
	}, {
		method: 'item.sku.update'
	}, {
		method: 'item.skus.get'
	}, {
		method: 'item.templates.get'
	}, {
		method: 'item.update'
	}, {
		method: 'item.update.delisting'
	}, {
		method: 'item.update.listing'
	}, {
		method: 'items.custom.get'
	}, {
		method: 'item.inventory.get'
	}, {
		method: 'items.list.get'
	}, {
		method: 'items.onsale.get'
	}, {
		method: 'product.add'
	}, {
		method: 'product.get'
	}, {
		method: 'product.img.delete'
	}, {
		method: 'product.img.upload'
	}, {
		method: 'product.propimg.delete'
	}, {
		method: 'product.propimg.upload'
	}, {
		method: 'product.update'
	}, {
		method: 'products.get'
	}, {
		method: 'products.search'
	}, {
		method: 'skus.custom.get'
	}, {
		method: 'skus.quantity.update'
	}, {
		method: 'topats.items.all.get'
	}, {
		method: 'ump.promotion.get'
	}, {
		method: 'brandcat.control.get'
	}, {
		method: 'brandcat.salespro.get'
	}, {
		method: 'product.spec.add'
	}, {
		method: 'product.spec.get'
	}, {
		method: 'product.spec.pic.upload'
	}, {
		method: 'product.specs.get'
	}
]);

